name: 02 - Workflow Events
on: 
    pull_request:
    workflow_dispatch:
jobs:
    echo:                                  #job number 1
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "I was triggered by a ${{github.event_name}}"

